### ISSUE TITLE
Build a docker image for the script 

### ISSUE THREAD

**Issue by deathvenom-369** [Drapersniper/Qbitrr#25]
[2022-01-21 11:48:33] [pid:    1911][tid:140218955368256] ERROR   : qBitrr.Sonarr-TV   : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/qBitrr/arss.py", line 1766, in process_torrents
    self.api_calls()
  File "/usr/local/lib/python3.8/dist-packages/qBitrr/arss.py", line 889, in api_calls
    self.post_command("RefreshMonitoredDownloads")
  File "/usr/local/lib/python3.8/dist-packages/qBitrr/arss.py", line 1733, in post_command
    res = self.client.request_post(path, data=data)
  File "/usr/local/lib/python3.8/dist-packages/pyarr/request_api.py", line 70, in request_post
    return res.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Removing blank line fixes error:
from __future__ import annotations

import contextlib
import itertools
import logging
import pathlib
import re
import sys
import time
from collections import defaultdict

To:
from __future__ import annotations
import contextlib
import itertools
import logging
import pathlib
import re
import sys
import time
from collections import defaultdict

**Comment by Drapersniper** [comment]
Just to check

```
from future import annotations

import contextlib
```
are you referencing this blank line between these 2 import statements?

If so thats not the source of the error you are seeing.


```py
self.post_command("RefreshMonitoredDownloads")
```

this is the source of the error - Meaning Sonarr returned a non json response.
Did your Sonarr instance become temporarely non-responsive ? 

Wasn't aware that that specific endpoint could return anything thats not a json response.

**Comment by Drapersniper** [comment]
Can you please also confirm which version of the script and Sonarr you are currently using.

**Comment by Drapersniper** [comment]
Thank I'll take a look at it, tomorrow not able to do it today.

Can you confirm your config values for Sonarr-TV ? make sure all the settings are correct

**Comment by deathvenom-369** [comment]
So I got it to work :) Turns out my weird networking set up was to blame. Inside my docker server like containers share a internal network with no port forwarding. They usually communicate on internal network via host-names. Management is threw reverse proxy only. I was unable to stably connect this way with script. Tho this is how sonarr communicates with qBittorrent. ended up passing communication threw reverse proxy.

Great script. I check torrents couple times a week hoping this brings that to once a month. THANK YOU!!

**Comment by Drapersniper** [comment]
I'll keep this issue open, seems like it may be worth while to build a docker image for it specially since I myself am moving to a full docker setup.

**Comment by Drapersniper** [comment]
@deathvenom-369 just in case you want, I've built a docker image to run the scrip, it uses pypy as a base so generally should be faster for this use case.

have a read of the README.md for more info if you have questions join the discord server and I'll be happy to answer any and all

**Comment by deathvenom-369** [comment]
Awesome! I think having a docker will simplify things while hopefully bring attention to this great project.

**Comment by Drapersniper** [comment]
please share your full config file removing ONLY API keys and URLs (keep paths intact, if you prefer join the discord and send me it in a DM)
