### ISSUE TITLE
qBitTorrent version

### ISSUE THREAD

**Issue by Skyline404** [Drapersniper/Qbitrr#58]
`CRITICAL: qBitrr.Manager : You are currently running qBitTorrent version 4.4.3.1, Supported version range is 4.3.4 to 4.4`

**Comment by Drapersniper** [comment]
Been super busy, I'll push a fix for this tomorrow

**Comment by Drapersniper** [comment]
Do note, The only testing done in BitTorrent 4.4+ was a while back and there were several issues on API side (i.e with BitTorrent)  - I use 4.3.9 and have for quite a while and that's the version qBitrr works best with.

On the commit above I unlocked the ability to run on 4.4, but if the API issues weren't resolved then know I expect you to see some issues
