### ISSUE TITLE
qBittorrent version must be < 4.5

### ISSUE THREAD

**Issue by enieuwy** [Drapersniper/Qbitrr#76]
Hi!

Thank you this this script. I'm using the docker container, but it restarts every few minutes and gives the error that the qBittorrent version must be lower than 4.5. I'm using 4.5.2.

Will this be updated for the latest version? Alternatively, is there a workaround?
Thank you!

**Comment by Drapersniper** [comment]
If someone makes a PR for it sure, I'm not working on this anymore since I no longer use qBittorrent
